version: "2"

issues:
  exclude-dirs:
    - vendor

  exclude-files:
    - ".*\\_test.go$"

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - nosprintfhostport
    - staticcheck
    - unused
    - copyloopvar

formatters:
  settings:
    gofmt:
      simplify: false
