/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	cloudprivateipconfigv1 "github.com/openshift/cloud-network-config-controller/pkg/crd/cloudprivateipconfig/v1"
	versioned "github.com/openshift/cloud-network-config-controller/pkg/crd/cloudprivateipconfig/v1/apis/clientset/versioned"
	internalinterfaces "github.com/openshift/cloud-network-config-controller/pkg/crd/cloudprivateipconfig/v1/apis/informers/externalversions/internalinterfaces"
	v1 "github.com/openshift/cloud-network-config-controller/pkg/crd/cloudprivateipconfig/v1/apis/listers/cloudprivateipconfig/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CloudPrivateIPConfigInformer provides access to a shared informer and lister for
// CloudPrivateIPConfigs.
type CloudPrivateIPConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CloudPrivateIPConfigLister
}

type cloudPrivateIPConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCloudPrivateIPConfigInformer constructs a new informer for CloudPrivateIPConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCloudPrivateIPConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCloudPrivateIPConfigInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredCloudPrivateIPConfigInformer constructs a new informer for CloudPrivateIPConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCloudPrivateIPConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1().CloudPrivateIPConfigs().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1().CloudPrivateIPConfigs().Watch(context.TODO(), options)
			},
		},
		&cloudprivateipconfigv1.CloudPrivateIPConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *cloudPrivateIPConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCloudPrivateIPConfigInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cloudPrivateIPConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cloudprivateipconfigv1.CloudPrivateIPConfig{}, f.defaultInformer)
}

func (f *cloudPrivateIPConfigInformer) Lister() v1.CloudPrivateIPConfigLister {
	return v1.NewCloudPrivateIPConfigLister(f.Informer().GetIndexer())
}
